# Generated by Django 4.2.4 on 2023-08-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stonk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('stonk_name', models.CharField()),
                ('stonk_symbol', models.CharField()),
                ('stonk_volume', models.IntegerField()),
                ('stonk_dividend', models.FloatField()),
                ('price_open', models.FloatField()),
                ('price_high', models.FloatField()),
                ('price_low', models.FloatField()),
                ('price_close', models.FloatField()),
            ],
        ),
    ]
