# Generated by Django 4.2.4 on 2023-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_app', '0002_stonk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonk',
            name='entry_date',
            field=models.DateTimeField(),
        ),
    ]
