# Generated by Django 4.2.4 on 2023-08-28 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_app', '0003_alter_stonk_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stonk',
            name='stonk_name',
        ),
    ]
